### ISSUE TITLE
nats: no server available

### ISSUE THREAD

**Issue by mrchandu** [mainflux/agent#33]
![nats_error](https://user-images.githubusercontent.com/31549436/80191880-fc25a100-8633-11ea-91dd-467b92dc9609.PNG)
I am able to connect to bootstrap and get data from mainflux, now I am stuck at nats server .
after getting data two toml files created export.toml and config.toml, what is the next step.
please help.

**Comment by mteodor** [comment]
Run nats server 
`go get github.com/nats-io/gnatsd`
`gnatsd`

**Comment by mrchandu** [comment]
@mteodor Thanks for the reply
![image](https://user-images.githubusercontent.com/31549436/80193588-b7e7d000-8636-11ea-9435-4a5e6f296f4b.png)
no response from gnatsd

**Comment by mteodor** [comment]
does your path includes gopath?

**Comment by mrchandu** [comment]
![image](https://user-images.githubusercontent.com/31549436/80193821-17de7680-8637-11ea-9de7-e91068e643d0.png)
Is this correct?

**Comment by mteodor** [comment]
This is my enviroment
```
GOPATH=/home/mirko/go
GOROOT=/usr/local/go
GOPATH=/home/mirko/go
PATH=/home/mirko/go/bin:/usr/local/go/bin:...
```

```
 ➜  go pwd   
/home/mirko/go
➜  go ls
bin  pkg  src

```

```
➜  bin pwd
/home/mirko/go/bin
➜  bin ls 
dep  dlv  gnatsd  golangci-lint  go-outline  gopls  gosh  
```

**Comment by drasko** [comment]
Closing this one, please reopen if needed.

@mteodor if NATS is a dependency for Agent, this must be noted in the documentation.
