### ISSUE TITLE
Undefined reference to 'gccgoRealSyscall' and 'gccgoRealSyscallNoError'

### ISSUE THREAD

**Issue by advancedwebdeveloper** [mainflux/agent#47]
Hi.
Here is my tryout to build your package, using [gollvm](https://go.googlesource.com/gollvm/)("llvm-goc"):

> $make

[full/verbose stdout output](https://gist.github.com/advancedwebdeveloper/22f63b64277a1192e384c85387283345)

I caught these errors:

> /home/oceanfish81/agent/vendor/golang.org/x/sys/unix/gccgo.go:55: error: undefined reference to 'gccgoRealSyscall'
> /home/oceanfish81/agent/vendor/golang.org/x/sys/unix/gccgo.go:30: error: undefined reference to 'gccgoRealSyscall'
> /home/oceanfish81/agent/vendor/golang.org/x/sys/unix/gccgo.go:23: error: undefined reference to 'gccgoRealSyscallNoError'
> /home/oceanfish81/agent/vendor/golang.org/x/sys/unix/gccgo.go:37: error: undefined reference to 'gccgoRealSyscall'
> /home/oceanfish81/agent/vendor/golang.org/x/sys/unix/gccgo.go:44: error: undefined reference to 'gccgoRealSyscall'
> /home/oceanfish81/agent/vendor/golang.org/x/sys/unix/gccgo.go:50: error: undefined reference to 'gccgoRealSyscallNoError'

This error does not arrive with CGO_ENABLED=1, despite that is not what you are targeting.
Just sharing for tracking down the cause, with CGO_ENABLED=0.

My environment look like this:
> $ go env
> GO111MODULE=""
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/oceanfish81/.cache/go-build"
> GOENV="/home/oceanfish81/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOINSECURE=""
> GOMODCACHE="/home/oceanfish81/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/oceanfish81/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/home/oceanfish81/gollvm_dist"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/home/oceanfish81/gollvm_dist/tools"
> GCCGO="/home/oceanfish81/gollvm_dist/bin/llvm-goc"
> AR="ar"
> CC="/usr/bin/clang"
> CXX="/usr/bin/clang++"
> CGO_ENABLED="1"
> GOMOD="/home/oceanfish81/agent/go.mod"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build482369313=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
> 

> $ go version
> go version go1.15.2 gollvm LLVM 12.0.0git linux/amd64

CC @thanm @cherrymui @ianlancetaylor

**Comment by drasko** [comment]
There are no C bindings in Mainflux.
